# -*- coding: utf-8 -*-
"""To-Do List CLI App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWgRKXEsn931OxrUU0jM5tcWfH49GkNJ
"""

# To-Do List CLI App

todo_list = []

def show_menu():
    print("\n📋 To-Do List App")
    print("1. ➕ Add Task")
    print("2. ✅ View Tasks")
    print("3. ❌ Remove Task")
    print("4. 🚪 Exit")

def add_task():
    task = input("Enter the task: ")
    todo_list.append(task)
    print(f"✅ Task added: {task}")

def view_tasks():
    if not todo_list:
        print("📭 No tasks in the list.")
    else:
        print("\n📌 Tasks:")
        for i, task in enumerate(todo_list, 1):
            print(f"{i}. {task}")

def remove_task():
    view_tasks()
    if todo_list:
        try:
            num = int(input("Enter task number to remove: "))
            removed = todo_list.pop(num - 1)
            print(f"❌ Removed: {removed}")
        except:
            print("⚠️ Invalid task number!")

# Main Loop
while True:
    show_menu()
    choice = input("Choose an option (1-4): ")

    if choice == "1":
        add_task()
    elif choice == "2":
        view_tasks()
    elif choice == "3":
        remove_task()
    elif choice == "4":
        print("👋 Exiting... Bye!")
        break
    else:
        print("⚠️ Invalid choice. Try again.")

